version: '3'

services:
   # Define the frontend service
   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     # Specify volumes/network
     volumes: 
      - wordpress:/var/www/html'
     ports:
       - "8000:80"
     restart: always
     # Environment variables
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress

   # Define the backend service
   db:
     image: mysql:latest
     # Specify volumes/network
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     # Environment variables
     environment:
       MYSQL_ROOT_PASSWORD: password
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress
volumes:
    wordpress:
    db_data: